### ISSUE TITLE
question

### ISSUE THREAD

**Issue by rkk1995** [SimonBaars/adventOfCode-2019#1]
Hi there. Not really an issue, but I'm learning java  from python and I was wondering how to initialy set up the whole directory. Do you use maven or how is it typically done? I'm using intellij community. Thanks

**Comment by SimonBaars** [comment]
Hello!

My project is indeed configured as a Maven project, so you can open it in IntelliJ as a Maven project (just go to `File -> Open` and select the project). IntelliJ will automatically recognize that it's a Maven project and import it correctly. I use some pretty recent Java features so you will need to have Java 13 installed. Then, go to the `Project settings` in IntelliJ (`Project` tab) and set the `Project SDK` to `13` and the `Project language level` to `13 (Preview)`. After that, you should be able to run the `Main` class to run all days.

**Comment by rkk1995** [comment]
I see. I want to do all the questions for myself though. I was just curious how to properly setup the environment in IntelliJ. So I should instal Maven plugin and create a new Maven project? Should I have 1 src folder with every Day[i].java file immediatley in that directory? Thanks again, getting used to java from python is tough 😢 

Can I do the questions with OpenJDK or should I switch to 11?

**Comment by SimonBaars** [comment]
Hey, then any version is right indeed. Select `File -> New -> Maven` and check the `Create from archetype` box, and then select `org.apache.maven.archetypes:maven-archetype-quickstart`. That will generate a whole project for you with a conventional folder structure and everything. Then you just create your java files in the `src/main/java` folder.
